
// This file was autogenerated by PeakRDL-uvm
package mi_periferico_pkg;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - MI_PERIFERICO::CONTROL
    class MI_PERIFERICO__CONTROL extends uvm_reg;
        rand uvm_reg_field ENABLE;
        rand uvm_reg_field MODE;

        function new(string name = "MI_PERIFERICO__CONTROL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.ENABLE = new("ENABLE");
            this.ENABLE.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.MODE = new("MODE");
            this.MODE.configure(this, 2, 1, "RW", 0, 'h1, 1, 1, 0);
        endfunction : build
    endclass : MI_PERIFERICO__CONTROL

    // reg - MI_PERIFERICO::STATUS
    class MI_PERIFERICO__STATUS extends uvm_reg;
        rand uvm_reg_field READY;
        rand uvm_reg_field ERROR;

        function new(string name = "MI_PERIFERICO__STATUS");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.READY = new("READY");
            this.READY.configure(this, 1, 0, "RO", 1, 'h1, 1, 1, 0);
            this.ERROR = new("ERROR");
            this.ERROR.configure(this, 1, 1, "W1C", 1, 'h0, 1, 1, 0);
        endfunction : build
    endclass : MI_PERIFERICO__STATUS

    // mem - my_memory
    class my_memory extends uvm_reg_block;
        rand uvm_mem m_mem;
        
        function new(string name = "my_memory");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4.0, UVM_LITTLE_ENDIAN);
            this.m_mem = new("m_mem", 256, 32, "RW");
            this.m_mem.configure(this);
            this.default_map.add_mem(this.m_mem, 0);
        endfunction : build
    endclass : my_memory

    // addrmap - MI_PERIFERICO
    class MI_PERIFERICO extends uvm_reg_block;
        rand MI_PERIFERICO__CONTROL CONTROL;
        rand MI_PERIFERICO__STATUS STATUS;
        rand my_memory my_mem_inst[1024];

        function new(string name = "MI_PERIFERICO");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_LITTLE_ENDIAN);
            this.CONTROL = new("CONTROL");
            this.CONTROL.configure(this);

            this.CONTROL.build();
            this.default_map.add_reg(this.CONTROL, 'h4);
            this.STATUS = new("STATUS");
            this.STATUS.configure(this);

            this.STATUS.build();
            this.default_map.add_reg(this.STATUS, 'h8);
            foreach(this.my_mem_inst[i0]) begin
                this.my_mem_inst[i0] = new($sformatf("my_mem_inst[%0d]", i0));
                this.my_mem_inst[i0].configure(this);
                this.my_mem_inst[i0].build();
                this.default_map.add_submap(this.my_mem_inst[i0].default_map, 'h1000 + i0*'h400);
            end
        endfunction : build
    endclass : MI_PERIFERICO

endpackage: mi_periferico_pkg
