// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module MI_PERIFERICO (
        input wire clk,
        input wire rst,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [20:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        input MI_PERIFERICO_pkg::MI_PERIFERICO__in_t hwif_in,
        output MI_PERIFERICO_pkg::MI_PERIFERICO__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [20:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk) begin
        if(rst) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[20:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;
    logic external_pending;

    // Read & write latencies are balanced. Stalls not required
    // except if external
    assign cpuif_req_stall_rd = external_pending;
    assign cpuif_req_stall_wr = external_pending;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic CONTROL;
        logic STATUS;
        logic my_mem_inst[1024];
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic decoded_req_is_external;

    logic [20:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        automatic logic is_external;
        is_external = '0;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.CONTROL = cpuif_req_masked & (cpuif_addr == 21'h4);
        decoded_reg_strb.STATUS = cpuif_req_masked & (cpuif_addr == 21'h8);
        for(int i0=0; i0<1024; i0++) begin
            decoded_reg_strb.my_mem_inst[i0] = cpuif_req_masked & (cpuif_addr >= 21'h1000 + (21)'(i0) * 21'h400) & (cpuif_addr <= 21'h1000 + (21)'(i0) * 21'h400 + 21'h3ff);
            is_external |= cpuif_req_masked & (cpuif_addr >= 21'h1000 + (21)'(i0) * 21'h400) & (cpuif_addr <= 21'h1000 + (21)'(i0) * 21'h400 + 21'h3ff);
        end
        decoded_err = '0;
        decoded_req_is_external = is_external;
    end
    logic external_wr_ack;
    logic external_rd_ack;
    always_ff @(posedge clk) begin
        if(rst) begin
            external_pending <= '0;
        end else begin
            if(decoded_req_is_external & ~external_wr_ack & ~external_rd_ack) external_pending <= '1;
            else if(external_wr_ack | external_rd_ack) external_pending <= '0;
            `ifndef SYNTHESIS
                assert_bad_ext_wr_ack: assert(!external_wr_ack || (external_pending | decoded_req_is_external))
                    else $error("An external wr_ack strobe was asserted when no external request was active");
                assert_bad_ext_rd_ack: assert(!external_rd_ack || (external_pending | decoded_req_is_external))
                    else $error("An external rd_ack strobe was asserted when no external request was active");
            `endif
        end
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } ENABLE;
            struct {
                logic [1:0] next;
                logic load_next;
            } MODE;
        } CONTROL;
        struct {
            struct {
                logic next;
                logic load_next;
            } ERROR;
        } STATUS;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } ENABLE;
            struct {
                logic [1:0] value;
            } MODE;
        } CONTROL;
        struct {
            struct {
                logic value;
            } ERROR;
        } STATUS;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: MI_PERIFERICO.CONTROL.ENABLE
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CONTROL.ENABLE.value;
        load_next_c = '0;
        if(decoded_reg_strb.CONTROL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CONTROL.ENABLE.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.CONTROL.ENABLE.next = next_c;
        field_combo.CONTROL.ENABLE.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.CONTROL.ENABLE.value <= 1'h0;
        end else begin
            if(field_combo.CONTROL.ENABLE.load_next) begin
                field_storage.CONTROL.ENABLE.value <= field_combo.CONTROL.ENABLE.next;
            end
        end
    end
    assign hwif_out.CONTROL.ENABLE.value = field_storage.CONTROL.ENABLE.value;
    // Field: MI_PERIFERICO.CONTROL.MODE
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.CONTROL.MODE.value;
        load_next_c = '0;
        if(decoded_reg_strb.CONTROL && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.CONTROL.MODE.value & ~decoded_wr_biten[2:1]) | (decoded_wr_data[2:1] & decoded_wr_biten[2:1]);
            load_next_c = '1;
        end
        field_combo.CONTROL.MODE.next = next_c;
        field_combo.CONTROL.MODE.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.CONTROL.MODE.value <= 2'h1;
        end else begin
            if(field_combo.CONTROL.MODE.load_next) begin
                field_storage.CONTROL.MODE.value <= field_combo.CONTROL.MODE.next;
            end
        end
    end
    assign hwif_out.CONTROL.MODE.value = field_storage.CONTROL.MODE.value;
    // Field: MI_PERIFERICO.STATUS.ERROR
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.STATUS.ERROR.value;
        load_next_c = '0;
        if(decoded_reg_strb.STATUS && decoded_req_is_wr) begin // SW write 1 clear
            next_c = field_storage.STATUS.ERROR.value & ~(decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end else begin // HW Write
            next_c = hwif_in.STATUS.ERROR.next;
            load_next_c = '1;
        end
        field_combo.STATUS.ERROR.next = next_c;
        field_combo.STATUS.ERROR.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.STATUS.ERROR.value <= 1'h0;
        end else begin
            if(field_combo.STATUS.ERROR.load_next) begin
                field_storage.STATUS.ERROR.value <= field_combo.STATUS.ERROR.next;
            end
        end
    end
    for(genvar i0=0; i0<1024; i0++) begin
        // External region: MI_PERIFERICO.my_mem_inst[]
        assign hwif_out.my_mem_inst[i0].req = decoded_reg_strb.my_mem_inst[i0];
        assign hwif_out.my_mem_inst[i0].addr = decoded_addr[9:0];
        assign hwif_out.my_mem_inst[i0].req_is_wr = decoded_req_is_wr;
        assign hwif_out.my_mem_inst[i0].wr_data = decoded_wr_data;
        assign hwif_out.my_mem_inst[i0].wr_biten = decoded_wr_biten;
    end

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    always_comb begin
        automatic logic wr_ack;
        wr_ack = '0;
        for(int i0=0; i0<1024; i0++) begin
            wr_ack |= hwif_in.my_mem_inst[i0].wr_ack;
        end
        external_wr_ack = wr_ack;
    end
    assign cpuif_wr_ack = external_wr_ack | (decoded_req & decoded_req_is_wr & ~decoded_req_is_external);
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------
    logic readback_external_rd_ack_c;
    always_comb begin
        automatic logic rd_ack;
        rd_ack = '0;
        for(int i0=0; i0<1024; i0++) begin
            rd_ack |= hwif_in.my_mem_inst[i0].rd_ack;
        end
        readback_external_rd_ack_c = rd_ack;
    end

    logic readback_external_rd_ack;

    assign readback_external_rd_ack = readback_external_rd_ack_c;

    logic [20:0] rd_mux_addr;
    logic [20:0] pending_rd_addr;
    // Hold read mux address to guarantee it is stable throughout any external accesses
    always_ff @(posedge clk) begin
        if(rst) begin
            pending_rd_addr <= '0;
        end else begin
            if(decoded_req) pending_rd_addr <= decoded_addr;
        end
    end
    assign rd_mux_addr = decoded_req ? decoded_addr : pending_rd_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 21'h4) begin
            readback_data_var[0] = field_storage.CONTROL.ENABLE.value;
            readback_data_var[2:1] = field_storage.CONTROL.MODE.value;
        end
        if(rd_mux_addr == 21'h8) begin
            readback_data_var[0] = hwif_in.STATUS.READY.next;
            readback_data_var[1] = field_storage.STATUS.ERROR.value;
        end
        for(int i0=0; i0<1024; i0++) begin
            if((rd_mux_addr >= 21'h1000 + (21)'(i0) * 21'h400) && (rd_mux_addr <= 21'h1000 + (21)'(i0) * 21'h400 + 21'h3ff)) begin
                readback_data_var = hwif_in.my_mem_inst[i0].rd_data;
            end
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr & ~decoded_req_is_external;
        readback_err = '0;
    end

    assign external_rd_ack = readback_external_rd_ack;
    assign cpuif_rd_ack = readback_done | readback_external_rd_ack;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
